server:
  port: 8080
  servlet:
    context-path: /
spring:
  application:
    name: mp-generator
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  main:
    allow-bean-definition-overriding: true

  shardingsphere:
    datasource:
      names: ds-master-0,ds-master-1
      ds-master-0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shard_one?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
      ds-master-1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/shard_two?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
    sharding:
      #表路由策略
      tables:
        user_info:
          actual-data-nodes: ds-master-$->{0..1}.user_info_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: user_info_$->{id % 2}
          key-generator:
            column: id
            type: SNOWFLAKE
      #数据库路由策略
      default-database-strategy:
        inline:
          sharding-column: id
          algorithm-expression: ds-master-$->{id % 2}
    props:
      sql:
        show: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      logic-delete-field: deleted
  mapper-locations: classpath:/mapper/**.xml